apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
  annotations:
    yandex.cloud/load-balancer-type: internal
    yandex.cloud/subnet-id: "{{SUBNET_ID}}"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fraud-api