apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
  annotations:
    yandex.cloud/load-balancer-type: internal
    # Добавьте эту строку (замените на ваш реальный ID подсети)
    yandex.cloud/subnet-id: e9b9dc7a9o07bm47nid4
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fraud-api