name: CI/CD

on:
  push:
    branches:
      - main

env:
  YC_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
  YC_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  YC_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  YC_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT_URL }}
  YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}

jobs:
  # 1. Анализатор изменений
  changes:
    runs-on: ubuntu-latest
    outputs:
      dags: ${{ steps.filter.outputs.dags }}
      src: ${{ steps.filter.outputs.src }}
      model: ${{ steps.filter.outputs.model }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dags: ['dags/**']
            src: ['src/**']
            inference: ['restapi/**', ]

  # 2. Синхронизация DAGs (ваша задача)
  sync-dags:
    needs: changes
    if: ${{ needs.changes.outputs.dags == 'true' }}
    name: Sync dags to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.YC_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ env.YC_S3_ENDPOINT }}
          SOURCE_DIR: 'dags'
          DEST_DIR: 'dags'

  upload-src:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    name: Upload Source code to S3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.YC_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ env.YC_S3_ENDPOINT }}
          SOURCE_DIR: 'src'
          DEST_DIR: 'src'

  build-and-deploy-model:
    needs: changes
    if: ${{ needs.changes.outputs.inference == 'true' }}
    name: Build Model and Update K8s Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Тесты
      - name: Install test dependencies
        run: |
          pip install pytest pandas numpy pydantic loguru mlflow pyspark
          
      - name: Run unit tests
        run: pytest restapi/tests/

      - name: Authenticate with Yandex Cloud
        uses: yc-actions/yc-setup@v2
        with:
          zb_sa_json_key: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Login to Registry
        run: yc container registry configure-docker

      - name: Build and Push Docker Image
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api:${{ github.sha }}
          docker build -t $IMAGE_PATH .
          docker push $IMAGE_PATH

      - name: Prepare and Upload K8s Manifest to S3
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api:${{ github.sha }}
          sed "s|{{IMAGE_PLACEHOLDER}}|$IMAGE_PATH|g" k8s/deployment-template.yaml > deployment.yaml
          
          aws s3 cp deployment.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/deployment.yaml \
            --endpoint-url ${{ env.YC_S3_ENDPOINT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}